services:
  db:
    image: mysql:8.4
    container_name: db.${PRJ_NAME}
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - TZ=$TZ
    volumes:
      - ./DB/mysql:/var/lib/mysql
      - ./CONFIG/mysql:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # healthcheck:
    #   test:
    #     [
    #       "CMD",
    #       "mysqladmin",
    #       "ping",
    #       "-u",
    #       "root",
    #       "-p${MYSQL_ROOT_PASSWORD}"
    #     ]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 20
    #   start_period: 30s
    restart: ${DOCKER_RESTART}
    networks:
      - mhmng-stack


  mh_mng:
    container_name: mh_mng.${PRJ_NAME}
    image: mh_mng/mh_mng_server:$PRJ_VERSION
    build:
      context: ./DOCKER/mh-mng/
      args:
        HTTP_PROXY: $HTTP_PROXY
        HTTPS_PROXY: $HTTPS_PROXY
        NO_PROXY: $NO_PROXY
        TZ: $TZ
    links:
      - db
    ports:
      - ${MH_PORT}:443
    volumes:
      - ./SOURCE/mh-mng/app:/app
      - ./CONFIG/mh-mng/nginx.conf:/etc/nginx/nginx.conf
      - ./CONFIG/mh-mng/mime.types:/etc/nginx/mime.types
      - ./CONFIG/mh-mng/uwsgi.ini:/etc/uwsgi.ini
      - ./CONFIG/mh-mng/supervisord.conf:/etc/supervisord.conf
      - ./LOG/mh-mng:/log
      - ./CERTS:/certs
    tty: true
    environment:
      - Flask_APP=/app/app.py
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTPS_PROXY
      - NO_PROXY=$NO_PROXY
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - no_proxy=$NO_PROXY
      - TZ=$TZ
      - CLIENT_MAX_BODY_SIZE=10M
      - MHMNG_DB_USER_NAME=$MHMNG_DB_USER_NAME
      - MHMNG_DB_USER_PASSWORD=$MHMNG_DB_USER_PASSWORD
      - MHMNG_DB_NAME=$MHMNG_DB_NAME
      - LOGLEVEL=$LOGLEVEL
    depends_on:
      db:
        # condition: service_healthy
        condition: service_started
    restart: ${DOCKER_RESTART}
    networks:
      - mhmng-stack

  # デバッグ用
  # phpmyadmin:
  #   container_name: phpmyadmin.${PRJ_NAME}
  #   image: phpmyadmin/phpmyadmin:latest
  #   ports:
  #     - ${PHPMYADIMN_PORT}:80
  #   links:
  #     - db
  #   depends_on:
  #     db:
  #       # condition: service_healthy
  #       condition: service_started
  #   environment:
  #     - MYSQL_USERNAME=root
  #     - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
  #     - TZ=$TZ
  #     - PMA_HOST=db
  #   restart: ${DOCKER_RESTART}
  #   networks:
  #     - mhmng-stack


networks:
  mhmng-stack:


