-- MySQL Script generated by MySQL Workbench
-- Tue Jan 21 19:45:28 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mhdb
-- -----------------------------------------------------
-- MH管理システム用DB バンニング計画、デバンニング計画

-- -----------------------------------------------------
-- Schema mhdb
--
-- MH管理システム用DB バンニング計画、デバンニング計画
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mhdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ;
CREATE USER IF NOT EXISTS 'mh'@'%' IDENTIFIED BY 'MHMNG_DB_USER_PASSWORD';
GRANT ALL PRIVILEGES ON mhdb.* TO 'mh'@'%';

USE `mhdb` ;

-- -----------------------------------------------------
-- Table `mhdb`.`devanning_plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mhdb`.`devanning_plan` ;

CREATE TABLE IF NOT EXISTS `mhdb`.`devanning_plan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mh` VARCHAR(16) NOT NULL COMMENT 'MHのGLN(3桁＋13桁)',
  `mh_space_list_str` VARCHAR(256) NOT NULL COMMENT 'MHの駐車枠のリスト（カンマ区切りの文字列）',
  `shipper_cid` VARCHAR(50) NULL COMMENT '荷主の事業者ID',
  `recipient_cid` VARCHAR(50) NULL COMMENT '荷受け人の事業者ID',
  `carrier_cid` VARCHAR(50) NULL COMMENT 'キャリアの事業者ID',
  `trsp_instruction_id` VARCHAR(20) NOT NULL COMMENT 'trsp_instruction_id',
  `tractor_giai` VARCHAR(34) NULL COMMENT '使用するトラクターのGIAI',
  `trailer_giai_list_str` VARCHAR(140) NULL COMMENT '使用するトレーラーのGIAIのリスト（カンマ区切りの文字列）',
  `req_from_time` DATETIME NULL COMMENT 'MH作業希望時間(From)',
  `req_to_time` DATETIME NULL COMMENT 'MH作業希望時間(To)',
  `actual_time` DATETIME NULL COMMENT 'MH作業実績時間',
  `status` INT NOT NULL COMMENT '状態(idle(0),planning(1),done(2),cancel(-1))',
  `is_bl_need` TINYINT NOT NULL DEFAULT 0 COMMENT 'B/L 検証有無(発MHのみ1,それ以外は0)',
  `is_departure_mh` TINYINT NOT NULL DEFAULT 1 COMMENT '発MHなら1、着MHなら0',
  `created_at` DATETIME NOT NULL COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL COMMENT '更新日時',
  PRIMARY KEY (`id`),
  INDEX `idx_mh` (`mh` ASC),
  INDEX `idx_req_from_time` (`req_from_time` ASC),
  INDEX `idx_req_to_time` (`req_to_time` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mhdb`.`vanning_plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mhdb`.`vanning_plan` ;

CREATE TABLE IF NOT EXISTS `mhdb`.`vanning_plan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mh` VARCHAR(16) NOT NULL COMMENT 'MHのGLN(3桁＋13桁)',
  `mh_space_list_str` VARCHAR(256) NOT NULL COMMENT 'MHの駐車枠のリスト（カンマ区切りの文字列）',
  `shipper_cid` VARCHAR(50) NULL COMMENT '荷主の事業者ID',
  `recipient_cid` VARCHAR(50) NULL COMMENT '荷受け人の事業者ID',
  `carrier_cid` VARCHAR(50) NULL COMMENT 'キャリアの事業者ID',
  `trsp_instruction_id` VARCHAR(20) NOT NULL COMMENT 'trsp_instruction_id',
  `tractor_giai` VARCHAR(34) NULL COMMENT '使用するトラクターのGIAI',
  `trailer_giai_list_str` VARCHAR(140) NULL COMMENT '使用するトレーラーのGIAIのリスト（カンマ区切りの文字列）',
  `req_from_time` DATETIME NULL COMMENT 'MH作業希望時間(From)',
  `req_to_time` DATETIME NULL COMMENT 'MH作業希望時間(To)',
  `actual_time` DATETIME NULL COMMENT 'MH作業実績時間',
  `status` INT NOT NULL COMMENT '状態(idle(0),planning(1),done(2),cancel(-1))',
  `is_bl_need` TINYINT NOT NULL DEFAULT 0 COMMENT 'B/L 検証有無(発MHのみ1,それ以外は0)',
  `is_departure_mh` TINYINT NOT NULL DEFAULT 1 COMMENT '発MHなら1、着MHなら0',
  `created_at` DATETIME NOT NULL COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL COMMENT '更新日時',
  PRIMARY KEY (`id`),
  INDEX `idx_mh` (`mh` ASC),
  INDEX `idx_req_from_time` (`req_from_time` ASC),
  INDEX `idx_req_to_time` (`req_to_time` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;





